### ISSUE TITLE
gallery images are too big

### ISSUE THREAD

**Issue by mikeyrayvon** [interglobalvision/apt25-com-mx#2]
http://apt25.com.mx/w/realmexicanstreetstyle-2/

these should be scaled down with image size

**Comment by mixcas** [comment]
what should be max-width? 904px?

**Comment by mixcas** [comment]
'feed-small' is 900,500, true

**Comment by varffs** [comment]
I generally go for whatever the max width of the css container is and for this kinda gallery probably yh like 2/3rds height. I guess we assume that when these are scaled down responsively they will roughly provide retina rez

**Comment by varffs** [comment]
The feed-square image is just under 2x its possible max css width. perhaps check all image sizes while your at this. Or maybe there is a retina intention with those image sizes? Quite slow to load on sub 3mb connection.

**Comment by mixcas** [comment]
feed-square? dont u mean "image-large"?

```
  add_image_size( 'admin-thumb', 150, 150, false );
  add_image_size( 'opengraph', 1200, 630, true );

  add_image_size( 'feed-square', 700, 700, true );
  add_image_size( 'feed-small', 900, 500, true );
  add_image_size( 'feed-large', 1200, 500, true );

  add_image_size( 'image-small', 700, 700, false );
  add_image_size( 'image-basic', 1000, 700, false );
  add_image_size( 'image-large', 1600, 1200, false );
```

**Comment by varffs** [comment]
No I mean feed-square. That image size can only be as large as 392x392px on the site. Check it out thats what I'm saying is probably worth doing.

**Comment by mixcas** [comment]
as large as 392px? where's that figure coming from? i see images as wide as 862px

![image](https://cloud.githubusercontent.com/assets/1994425/9206402/321f046a-402d-11e5-8b68-9e94416d5434.png)

container max is 932px
![screen shot 2015-08-11 at 1 31 11 pm](https://cloud.githubusercontent.com/assets/1994425/9206430/56917bde-402d-11e5-84cd-085c35a29b95.png)

**Comment by mixcas** [comment]
i see what u r talking about @varffs. i opened #3

**Comment by mixcas** [comment]
I'm gonna use  `image-large` for the gallery since its almost 2x the max width.

**Comment by mixcas** [comment]
70faedfd825fe6b813ef3de3d51bad56c3a202b3 closes this
